export {default as Navbar} from "./Navbar/Navbar"
export {default as Hero} from "./Hero/Hero"
export {default as Products} from "./Products/Products"
export {SlideImages} from "./SlideImages/SlideImages"
export {SlideMarketing} from "./SlideImages/SlideImages"